name: Build & Deploy
on:
  push:
    branches: 
    - master
    - feature/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          password: ''
     
          script: |
            cd app/teste-blockchain
            git pull
            yarn install
            pm2 start ecosystem.config.js --env production
            pm2 save
