name: Build & Deploy
on:
  push:
    branches: 
    - master
    - feature/deploy


jobs:
  start_deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USERNAME }}
    steps:
    - run: |

        apt update && apt install sudo curl && curl -sL https://raw.githubusercontent.com/Unitech/pm2/master/packager/setup.deb.sh | sudo -E bash -

        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ./deploy.key
        sudo chmod 600 ./deploy.key

        env

        pm2 deploy app
