name: Build & Deploy
on:
  push:
    branches: 
    - master
    - feature/deploy


jobs:
  start_deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
    steps:
    - uses: actions/checkout@v2
    - name: Install PM2
      run: |
        npm i pm2 -g

    - name: deploy app
      run: |

        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/deploy.key
        sudo chmod 600 ~/.ssh/deploy.key

        pm2 deploy app --force
