name: Build & Deploy
on:
  push:
    branches: 
    - master
    - feature/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
     
          script: |
            cd app/teste-blockchain
            git pull
            yarn install
            pm2 start ecosystem.config.js --env production
