name: Build & Deploy
on:
  push:
    branches: 
    - master
    - feature/deploy


jobs:
  start_deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USERNAME }}
    steps:
    - name: Install PM2
      run: npm i pm2 -g

    - name: deploy app
      run: |

        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ./deploy.key
        sudo chmod 600 ./deploy.key
        
        ls -lah
        
        pm2 deploy app
